// <auto-generated />
using System;
using CurlyQueens.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurlyQueens.Migrations
{
    [DbContext(typeof(MyAppdbcontext))]
    [Migration("20251110132321_addAuthTables")]
    partial class addAuthTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CurlyQueens.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CurlyQueens.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CurlyQueens.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CurlyQueens.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "منتجات لتغذية وترطيب الشعر الكيرلي وتحديد شكل الكيرلز",
                            Name = "Leave-in & Creams"
                        },
                        new
                        {
                            Id = 2,
                            Description = "جل ومواد تثبيت تحافظ على شكل الكيرلز بعد التصفيف",
                            Name = "Gels & Stylers"
                        },
                        new
                        {
                            Id = 3,
                            Description = "ماسكات عناية وترطيب عميق لعلاج الشعر الكيرلي",
                            Name = "Masks & Treatments"
                        },
                        new
                        {
                            Id = 4,
                            Description = "أجهزة تصفيف وتنشيف الشعر مثل الديفيوزر والنانو البخاري",
                            Name = "Devices"
                        },
                        new
                        {
                            Id = 5,
                            Description = "فرش وأمشاط مخصصة لفك التشابك وتحديد الكيرلز",
                            Name = "Brushes & Combs"
                        },
                        new
                        {
                            Id = 6,
                            Description = "توك وبونيهات وأكسسوارات تحافظ على الشعر الكيرلي",
                            Name = "Accessories & Satin"
                        },
                        new
                        {
                            Id = 7,
                            Description = "هير بيس وورد للعرايس والتسريحات الخاصة",
                            Name = "Hair Pieces & Bridal"
                        },
                        new
                        {
                            Id = 8,
                            Description = "شامبوهات وبلسم مخصصة للشعر الكيرلي",
                            Name = "Shampoo & Conditioner"
                        },
                        new
                        {
                            Id = 9,
                            Description = "سكرابات لفروة الرأس ومنتجات تنظيف عميق",
                            Name = "Scrubs & Scalp Care"
                        });
                });

            modelBuilder.Entity("CurlyQueens.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CurlyQueens.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CurlyQueens.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "كريم كيرلي غني بالزبدة لترطيب وتنعيم الشعر",
                            ImageUrl = "/images/cantu-leavein.jpg",
                            Name = "Cantu Shea Butter Leave-In",
                            Price = 250m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "كريم تعزيز الكيرلز من شيا مويسشر",
                            ImageUrl = "/images/sheamoisture-smoothie.jpg",
                            Name = "SheaMoisture Curl Enhancing Smoothie",
                            Price = 320m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "جل تثبيت ناعم بزيت الزيتون يحافظ على شكل الكيرلز",
                            ImageUrl = "/images/eco-gel.jpg",
                            Name = "Eco Styler Olive Oil Gel",
                            Price = 180m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "جل تحديد الكيرلز بخلاصة جوز الهند",
                            ImageUrl = "/images/jackie-gel.jpg",
                            Name = "Aunt Jackie's Curl Boss Gel",
                            Price = 210m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "ماسك علاجي بزيت باباسو لترطيب الشعر الجاف",
                            ImageUrl = "/images/mielle-mask.jpg",
                            Name = "Mielle Organics Babassu Oil Mask",
                            Price = 350m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "ماسك ترطيب عميق يصلح الشعر المتضرر",
                            ImageUrl = "/images/olaplex-mask.jpg",
                            Name = "Olaplex No.8 Moisture Mask",
                            Price = 480m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "دفيوزر لتنشيف الشعر الكيرلي بدون هيشان",
                            ImageUrl = "/images/diffuser.jpg",
                            Name = "Diffuser Professional Dryer",
                            Price = 600m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "جهاز بخار نانو لزيادة امتصاص الماسك وترطيب الشعر",
                            ImageUrl = "/images/nano-steamer.jpg",
                            Name = "Nano Steamer",
                            Price = 950m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "فرشة دنمان الكلاسيكية لتحديد الكيرلز",
                            ImageUrl = "/images/denman-brush.jpg",
                            Name = "Denman Brush D3",
                            Price = 230m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "مشط واسع الأسنان لفك التشابك بدون تقطيع",
                            ImageUrl = "/images/comb.jpg",
                            Name = "Wide Tooth Comb",
                            Price = 90m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Description = "بونيه ستان يحافظ على شكل الكيرلز أثناء النوم",
                            ImageUrl = "/images/satin-bonnet.jpg",
                            Name = "Satin Bonnet",
                            Price = 120m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Description = "توك ستان ناعمة للشعر الكيرلي",
                            ImageUrl = "/images/satin-scrunchies.jpg",
                            Name = "Satin Scrunchies Set",
                            Price = 80m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            Description = "هير بيس كيرلي للعرايس والتصوير",
                            ImageUrl = "/images/curly-bridal.jpg",
                            Name = "Curly Bridal Hair Piece",
                            Price = 400m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            Description = "إكسسوار شعر ورد أبيض أنيق",
                            ImageUrl = "/images/flower-accessory.jpg",
                            Name = "White Flower Hair Accessory",
                            Price = 150m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            Description = "شامبو مرطب بجوز الهند للشعر الكيرلي",
                            ImageUrl = "/images/maui-shampoo.jpg",
                            Name = "Maui Moisture Curl Shampoo",
                            Price = 250m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 8,
                            Description = "بلسم مغذي بجوز الهند للشعر الكيرلي",
                            ImageUrl = "/images/maui-conditioner.jpg",
                            Name = "Maui Moisture Conditioner",
                            Price = 250m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 9,
                            Description = "سكراب لفروة الرأس ينظفها بعمق ويحسن الدورة الدموية",
                            ImageUrl = "/images/scalp-scrub.jpg",
                            Name = "Scalp Scrub with Sea Salt",
                            Price = 200m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CurlyQueens.Models.CartItem", b =>
                {
                    b.HasOne("CurlyQueens.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CurlyQueens.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CurlyQueens.Models.OrderItem", b =>
                {
                    b.HasOne("CurlyQueens.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CurlyQueens.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CurlyQueens.Models.Product", b =>
                {
                    b.HasOne("CurlyQueens.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CurlyQueens.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CurlyQueens.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CurlyQueens.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CurlyQueens.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CurlyQueens.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("CurlyQueens.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CurlyQueens.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
